<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\christmas.glb -T --draco /draco
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/christmas-transformed.glb', { useDraco: '/draco' })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="metarig" position={[0.52, -0.02, 0]} rotation={[0, -0.06, 0]}>
        <T is={gltf.nodes.spine} />
        <T.Group name="snoo">
          <T.SkinnedMesh
            name="Head_Collapsed"
            geometry={gltf.nodes.Head_Collapsed.geometry}
            material={gltf.materials['Material.002']}
            skeleton={gltf.nodes.Head_Collapsed.skeleton}
          />
          <T.SkinnedMesh
            name="Head_Collapsed_1"
            geometry={gltf.nodes.Head_Collapsed_1.geometry}
            material={gltf.materials['Material.001']}
            skeleton={gltf.nodes.Head_Collapsed_1.skeleton}
          />
          <T.SkinnedMesh
            name="Head_Collapsed_2"
            geometry={gltf.nodes.Head_Collapsed_2.geometry}
            material={gltf.materials['Material.003']}
            skeleton={gltf.nodes.Head_Collapsed_2.skeleton}
          />
        </T.Group>
      </T.Group>
      <T.Mesh
        name="tree"
        geometry={gltf.nodes.tree.geometry}
        material={gltf.materials.Material_0}
        position={[-0.08, 1, -0.07]}
        rotation={[0, -0.07, 0]}
      />
      <T.Mesh
        name="gitfs"
        geometry={gltf.nodes.gitfs.geometry}
        material={gltf.materials['Material_0.001']}
        position={[-0.79, 0.42, 0.39]}
        rotation={[0, 0.39, 0]}
        scale={0.49}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
